### ISSUE TITLE
1.安装教程/打包 2.python-requests依赖

### ISSUE THREAD

**Issue by Firestar-Reimu** [YidaozhanYa/v2rayATray#1]
1. 能否提供 AUR/deb/rpm 打包或者安装教程
2. 我用`makepkg -si`安装后发现报错`ModuleNotFoundError: No module named 'requests'`，需要在 PKGBUILD 中增加一条 `python-requests`

**Comment by YidaozhanYa** [comment]
1: 有 Makefile
2: 已修复
